// Mock data for testing without MongoDB
const mockProducts = [
  {
    _id: "1",
    name: "Organic Bananas",
    price: 2.99,
    category: "fruits",
    isSustainable: true,
    ecoScore: 85,
    image: "/images/products/product-1-bananas.svg",
    rating: 4.5,
    reviews: 234,
  },
  {
    _id: "2",
    name: "Greek Yogurt",
    price: 4.99,
    category: "dairy",
    isSustainable: true,
    ecoScore: 75,
    image: "/images/products/product-2-yogurt.svg",
    rating: 4.3,
    reviews: 178,
  },
  {
    _id: "3",
    name: "Whole Grain Bread",
    price: 3.49,
    category: "bakery",
    isSustainable: true,
    ecoScore: 70,
    image: "/images/products/product-3-bread.svg",
    rating: 4.1,
    reviews: 156,
  },
  {
    _id: "4",
    name: "Almond Milk",
    price: 3.99,
    category: "dairy",
    isSustainable: true,
    ecoScore: 80,
    image: "/images/products/product-4-almond-milk.svg",
    rating: 4.4,
    reviews: 142,
  },
  {
    _id: "5",
    name: "Organic Chicken Breast",
    price: 12.99,
    category: "meat",
    isSustainable: true,
    ecoScore: 65,
    image: "/images/products/product-5-chicken.svg",
    rating: 4.2,
    reviews: 98,
  },
  {
    _id: "6",
    name: "Brown Rice",
    price: 2.49,
    category: "grains",
    isSustainable: true,
    ecoScore: 90,
    image: "/images/products/product-6-rice.svg",
    rating: 4.6,
    reviews: 201,
  },
  {
    _id: "7",
    name: "Fresh Spinach",
    price: 2.99,
    category: "vegetables",
    isSustainable: true,
    ecoScore: 95,
    image: "/images/products/product-7-spinach.svg",
    rating: 4.7,
    reviews: 187,
  },
  {
    _id: "8",
    name: "Quinoa",
    price: 5.99,
    category: "grains",
    isSustainable: true,
    ecoScore: 88,
    image: "/images/products/product-8-quinoa.svg",
    rating: 4.4,
    reviews: 146,
  },
  {
    _id: "9",
    name: "Milk",
    price: 3.29,
    category: "dairy",
    isSustainable: false,
    ecoScore: 60,
    image: "/images/products/product-9-milk.svg",
    rating: 4.0,
    reviews: 215,
  },
  {
    _id: "10",
    name: "Bread",
    price: 2.99,
    category: "bakery",
    isSustainable: false,
    ecoScore: 55,
    image: "/images/products/product-10-bread.svg",
    rating: 3.9,
    reviews: 126,
  },
  {
    _id: "11",
    name: "Butter",
    price: 4.49,
    category: "dairy",
    isSustainable: false,
    ecoScore: 50,
    image: "/images/products/product-11-butter.svg",
    rating: 4.2,
    reviews: 89,
  },
  {
    _id: "12",
    name: "Eggs",
    price: 3.99,
    category: "dairy",
    isSustainable: true,
    ecoScore: 75,
    image: "/images/products/product-12-eggs.svg",
    rating: 4.5,
    reviews: 167,
  },
];

module.exports = mockProducts;
